{% set name = "refactor" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/refactor-{{ version }}.tar.gz
  sha256: 3761ba8a422f82df9032b4e0dad5113487168dd7a28ce68c13642f81d548495b

build:
  number: 0
  noarch: python
  entry_points:
    - refactor = refactor.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=40.8.0
  run:
    - python >=3.9

test:
  imports:
    - refactor
  commands:
    - pip check
    - refactor --help
  requires:
    - pip

about:
  home: https://github.com/isidentical/refactor
  summary: AST based source code refactor interface
  doc_url: https://refactor.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
