{% set name = "refactor" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/refactor-{{ version }}.tar.gz
  sha256: 9c79c1da80cdb2fccddca24b32a2b1cef0c182fa8c070cd3b9b98cd1c9266deb

build:
  number: 0
  noarch: python
  entry_points:
    - refactor = refactor.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=40.8.0
  run:
    - python >=3.9

test:
  imports:
    - refactor
  commands:
    - pip check
    - refactor --help
  requires:
    - pip

about:
  home: https://github.com/isidentical/refactor
  summary: AST based source code refactor interface
  doc_url: https://refactor.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
